### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by rostykbest** [rostykbest/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by johncollaborator** [comment]
**DONALD TRUMP**

- fb.com/DonaldTrump

- twitter.com/realDonaldTrump

- instagram.com/realDonaldTrump
